### ISSUE TITLE
Add request number to CallbackHost

### ISSUE THREAD

**Issue by theblackturtle** [Damian89/extended-ssrf-search#7]
Hi, I think It will be nice if we adding request number to Callback Host like
- *.1111.g2jnwmvjno8sbwx6racij7fjya44sa.burpcollaborator.net
- gdd-threatmap.2222.bitdefender.com.g2jnwmvjno8sbwx6racij7fjya44sa.burpcollaborator.net
It would be very useful to track it come from which url.

**Comment by dark-warlord14** [comment]
This is must. I mean I am struggling right now to identify which request trigger the http request to my server. I am just splitting the urls in half and running it again like binary search.
But if any feature is added to make every server unique, it will be very helpful to identify the cause of the http request.

**Comment by amiralkizaru** [comment]
@dark-warlord14  @theblackturtle 

In the config file there is a a variable called `$(hostname)` You can use it for that burp
`$(hostname).yourburpcollab`
![here123](https://user-images.githubusercontent.com/32225186/79597063-87a1ae00-80d9-11ea-8456-af56e8600d72.JPG)

Hope this help
