### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by eduucateed** [Damian89/extended-ssrf-search#8]
when running it i get an error like this, can anyone help? thank you

~/extended-ssrf-search# python3 extended-ssrf-search.py
Traceback (most recent call last):
  File "extended-ssrf-search.py", line 84, in <module>
    main()
  File "extended-ssrf-search.py", line 38, in main
    config = Config()
  File "/root/extended-ssrf-search/inc/Config.py", line 33, in __init__
    self.__set_set_config()
  File "/root/extended-ssrf-search/inc/Config.py", line 48, in __set_set_config
    self.callback = self.config["default"]["CallbackHost"]
  File "/usr/lib/python3.6/configparser.py", line 959, in __getitem__
    raise KeyError(key)
KeyError: 'default'

**Comment by TGRBirdFlying** [comment]
> when running it i get an error like this, can anyone help? thank you
> 
> ~/extended-ssrf-search# python3 extended-ssrf-search.py
> Traceback (most recent call last):
> File "extended-ssrf-search.py", line 84, in 
> main()
> File "extended-ssrf-search.py", line 38, in main
> config = Config()
> File "/root/extended-ssrf-search/inc/Config.py", line 33, in **init**
> self.__set_set_config()
> File "/root/extended-ssrf-search/inc/Config.py", line 48, in __set_set_config
> self.callback = self.config["default"]["CallbackHost"]
> File "/usr/lib/python3.6/configparser.py", line 959, in **getitem**
> raise KeyError(key)
> KeyError: 'default'

That's the question I want to ask. Did you solve it?

**Comment by Damian89** [comment]
Looks like your config files are wrong.
